appname = crud_educacion
httpport = 8083
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres@localhost:5433/financeup?sslmode=disable&search_path=educacion
